List<String> frases = [
"No me diga que el cielo es el límite cuando hay huellas en la luna.",
"Un mal plan, es mejor que no tener ningún plan.",
"Todo lo que siempre has querido está al otro lado del miedo.",
"Para tener éxito, primero debemos creer que podemos hacerlo.",
"Para lograr grandes cosas, debemos vivir como si nunca fuéramos a morir.",
"Si puedes soñarlo, puedes hacerlo.",
"Si crees que algo es imposible, tú lo harás imposible.",
"El no querer es la causa, el no poder el pretexto.",
"No duermas para descansar, duerme para soñar. Porque los sueños están para cumplirse.",
"Hoy vas a conquistar el cielo, sin mirar lo alto que queda el suelo.",
"Los sueños son sumamente importantes. Nada se hace sin que antes se imagine.",
"Cáete siete veces y levántate ocho.",
"El poder de la imaginación nos hace infinitos.",
"Debes hacer las cosas que crees que no puedes hacer.",
"No puedes escoger cómo vas a morir o cuándo. Sólo puedes decidir cómo vivir ahora.",
"La fortuna favorece al valiente.",
"No cuentes los días, haz que los días cuenten.",
"Deja de pensar en la vida y resuélvete a vivirla.",
"Si te caíste ayer, levántate hoy.",
"La edad no es barrera. Es una limitación que pones en tu mente.",
"He fallado una y otra vez en mi vida, por eso he conseguido el éxito.",
"Donde una puerta se cierra, otra se abre.",
"Cuando las cosas van mal, no te vayas con ellas.",
"Nunca desistas de un sueño. Sólo trata de ver las señales que te lleven a él.",
"Si supiera que el mundo se acaba mañana, yo, hoy todavía, plantaría un árbol.",
"La perseverancia no es una carrera larga; es muchas carreras cortas una tras otra.",
"Hay un solo rincón del universo que puedes estar seguro de poder mejorar, y eres tú mismo.",
"Saber no es suficiente; debemos aplicarlo. La voluntad no es suficiente; debemos hacerlo.",
"Mientras más difícil el conflicto, más glorioso el triunfo.",
"¿Quieres saber quién eres? No lo preguntes. ¡Actúa! La acción te delimita y te define.",
"Haz las cosas difíciles mientras son fáciles y haz las grandes cosas mientras son pequeñas.",
"Un viaje de mil millas debe comenzar con un sólo paso.",
"El futuro no está prometido a nadie.",
"No se trata de si te derriban; se trata de si te levantas.",
"La posibilidad de realizar un sueño es lo que hace que la vida sea interesante.",
"Es mejor viajar lleno de esperanza que llegar.",
"Solo yo puedo cambiar mi vida. Nadie lo puede hacer por mí.",
"Cuando llegues al final de tu cuerda, haz un nudo y aguanta.",
"Nuestra mayor debilidad está en darnos por vencidos. La manera más acertada para tener éxito es siempre intentarlo sólo una vez más.",
"Cuando algo es lo suficientemente importante, lo haces incluso si las probabilidades de que salga bien no te acompañan.",
"No importa que tan lento vayas siempre y cuando no pares.",
"Recuerda mirar arriba, a las estrellas, y no abajo, a tus pies. Intenta encontrar el sentido a lo que ves, y pregúntate qué es lo que hace que el universo exista. Sé curioso. Y por muy difícil que te parezca la vida, siempre hay algo que puedes hacer y en lo que puedes tener éxito.",
"Lo único que cuenta es no rendirse.",
"Stephen Hawking nos dejó con esta preciosa frase motivadora que anima a no rendirse nunca. Ilumina el mañana con el presente.",
"Haz la única cosa que crees que no se puede hacer. Falla en ello. Prueba una vez más. Hazlo mejor la segunda vez. Las únicas personas que nunca caen son aquellas que nunca montan el cable alto. Este es tu momento. Poséelo.",
"Apunta hacia la luna. Si fallas, puede que le des a una estrella.",
"Haz tu trabajo con todo tu corazón y tendrás éxito; hay muy poca competencia.",
"Después de la tormenta siempre llega la calma.",
"No puede cruzar el mar simplemente estando de pie y mirando el agua.",
"Bien hecho es mejor que bien dicho.",
"Siempre intentaste. Siempre fallaste. No importa. Intenta de nuevo. Falla de nuevo. Falla mejor.",
"El éxito llega para todos aquellos que están ocupados buscándolo.",
"Nunca eres demasiado viejo para tener otra meta u otro sueño.",
"No habrá nada que te pueda asustar si te niegas a tener miedo.",
"El mejor momento del día es ahora.",
"La única diferencia entre un buen y mal día es tu actitud.",
"Siempre es temprano para rendirse.",
"Nunca podrás derrotar a la persona que nunca se rinde.",
"Con el nuevo día vienen nuevas fuerzas y nuevos pensamientos.",
"El mejor placer en la vida es hacer las cosas que la gente dice que no podemos hacer.",
"No tengo miedo a morir, tengo miedo a no intentarlo.",
"El secreto para salir adelante es comenzar.",
"Terminamos la lista con una reflexión de Mark Twain que anima a dar primer paso.",
"El misterio de la vida no es un problema a resolver, sino una realidad a experimentar (Duna, Frank Herbert) La importancia de la experiencia es lo que realmente nos hace vivir. Sólo en ésta podemos conocer el misterio de la vida.",
"Estar solo no tiene nada que ver con cuantas personas hay alrededor (Revolutionary Road, Richard Yates) La soledad es un sentimiento que, generalmente, viene asociado con una enorme tristeza. Puedes tener mucha gente a tu alrededor, pero sentirte increíblemente solo.",
"Sea un hombre o sea más que un hombre. Sea firme con su propósito y firme como una piedra (Frankestein, Mary Shelley) Hay que seguir adelante y no dejar atrás tus aspiraciones. Sólo así seguirás sintiéndote vivo.",
"El hombre débil se vuelve fuerte cuando no tiene nada, porque sólo entonces puede sentir la locura de la desesperación (La compañía blanca, Arthur Conan Doyle) Es en los peores momento cuando podemos crecer más que nunca. Hay que aprender de lo malo. ",
"Si buscas la perfección nunca estarás contento (Anna Karenina, Leo Tolstoy) Las personas perfeccionistas son increíblemente infelices.",
"Mientras el corazón late, mientras el cuerpo y alma siguen juntos, no puedo admitir que cualquier criatura dotada de voluntad tiene necesidad de perder la esperanza en la vida (Viaje al centro de la tierra, Julio Verne) Una gran frase pronunciada por Julio Verne en su obra más conocida.",
"No puedo morir aún doctor. Todavía no. Tengo cosas que hacer. Después de todo, tendré una vida entera en la que morir (El Juego del Ángel, Carlos Ruiz Zafón) La fuerza de la esperanza nos mantiene vivos en los momentos más delicados.",
"Tengo esperanza o podría no vivir (La isla del doctor Moreau, H.G. Wells) Igual que en el punto anterior, sin la esperanza no nos queda nada.",
"Llamo a la gente “rica” cuando son capaces de satisfacer las necesidades de su imaginación (El retrato de una dama, Henry James) Una oración de Henry James que habla del pensamiento de la gente rica.",
"El sol es débil cuando se eleva primero, y cobra fuerza y coraje a medida que avanza el día (Vieja tienda de curiosidades, Charles Dickens) Unas bonitas palabras que expresan la grandiosidad del sol, la estrella que nos da luz y calor.",
"Es en las noches de diciembre, cuando el termómetro está a cero, cuando más pensamos en el sol (Los miserables, Victor Hugo) Esta frase nos recuerda que si cuando tenemos algo no lo valoramos, cuando lo perdemos lo echamos de menos",
"Cada libro, cada volumen que ves aquí, tiene un alma. El alma de la persona que lo escribió y de aquellos que lo leyeron, vivieron y soñaron con él. Cada vez que un libro cambia de manos, cada vez que alguien baja sus ojos a las páginas, su espíritu crece y se fortalece (La Sombra del Viento, Carlos Ruiz Zafón) Carlos Ruiz Zafón, uno de lo grandes escritores españoles, nos cuenta la inmensidad de los libros y lo apasionados que son los escritores cuando dan vida a sus relatos.",
"Mi consejo es: nunca hagas mañana lo que puedes hacer hoy. La procrastinación es la ladrona del tiempo (David Copperfield, Charles Dickens) Charles Dickens nos habla que no debemos ser procrastinadores.",
"Luchar hasta el último aliento (Enrique VI, William Shakespeare)",
"Conseguir lo que quieres es tan difícil como no conseguir lo que quieres. Porque entonces tienes que averiguar qué hacer con ello, en lugar de averiguar qué hacer sin ello. (El reino de la posibilidad, David Levithan)",
"Deja de preocuparte por envejecer y piensa en crecer (El animal moribundo, Philip Roth)",
"Para ser feliz hay que pensar en seguir creciendo continuamente y uno debe continuar desarrollándose.",
"Crearía un perfume que no sólo fuera humano, sino sobrehumano. Un aroma de ángel, tan indescriptiblemente bueno y pletórico de vigor que quien lo oliera quedaría hechizado y no tendría más remedio que amar a la persona que lo llevara, o sea, amarle a él, Grenouille, con todo su corazón (El Perfume, Patrick Süskind)",
"¡Qué maravilloso es que nadie necesite esperar ni un solo momento antes de comenzar a mejorar el mundo! (El Diario de Ana Frank, Ana Frank)",
"Crees que sabes todas tus posibilidades. Entonces, otras personas llegan a tu vida y de repente hay muchas más (El reino de la posibilidad, David Levithan)",
"Las posibilidades aumentan a medida que conocemos gente nueva. Lo importante es estar en movimiento. Así las cosas llegan.",
"Nada hay en el mundo, ni hombre ni diablo ni cosa alguna, que sea para mí tan sospechoso como el amor, pues éste penetra en el alma más que cualquier otra cosa. Nada hay que ocupe y ate más al corazón que el amor. Por eso, cuando no dispone de armas para gobernarse, el alma se hunde, por el amor, en la más honda de las ruinas (El Nombre de la Rosa, Umberto Eco)",
"Seas quien seas, hagas lo que hagas, cuando deseas con firmeza alguna cosa es porque este deseo nació en el alma del universo. Es tu misión en la tierra (El Alquimista, Paulo Coelho)",
"El hombre llega mucho más lejos para evitar lo que teme que para alcanzar lo que desea (El Código da Vinci, Dan Brown)",
"Las situaciones negativas pueden ser positivas para ayudarnos a crecer y a desarrollarnos como personas.",
"Nuestras vidas se definen por las oportunidades, incluso las que perdemos (El curioso caso de Benjamin Button, F. Scott Fitzgerald)",
"Las oportunidades que perdemos, nos guste o no, también son parte de nuestra vida y nos marcan.",
"No todo lo que es de oro reluce, ni toda la gente errante anda perdida (El Señor de los Anillos, J.R.R. Tolkien)",
"Amor y deseo son dos cosas diferentes; que no todo lo que se ama se desea, ni todo lo que se desea se ama (Don Quijote de la Mancha, Miguel de Cervantes)",
"Cuando te hayas consolado, te alegrarás de haberme conocido (El Principito, Antoine de Saint-Exupèry)",
"Era el mejor de los tiempos, era el peor de los tiempos, era la edad de la sabiduría, era la edad de la insensatez, era la época de la creencia, era la época de la incredulidad, era la estación de la luz, era la estación de la oscuridad, era la primavera de la esperanza, era el invierno de la desesperación (Historia de dos Ciudades, Charles Dickens)",
"Y una vez disipados los malos olores del pasado, quería ahora inundarlo de fragancias (El Perfume, Patrick Süskind)",
"Cuando superas las cosas malas que te han podido suceder, el futuro y el presente te parecen menos malos.",
"No soy un pájaro y ninguna red me atrapa. Soy un ser humano libre con una voluntad independiente (Jane Eyre, Charlotte Bronte)",
"La mayor aventura es la que nos espera. Hoy y mañana aún no se han dicho. Las posibilidades, los cambios son todos vuestros por hacer. El molde de su vida en sus manos está para romper (El Hobbit, J.R.R. Tolkien)",
"Nosotros podemos, al menos en gran medida, elegir el camino que queremos seguir en la vida. De nosotros depende esforzarnos para lograr las metas que tengamos en mente.",
"Siento que me estoy moviendo hacia delante a la vez que alejándome de algo, y todo es posible (American Psycho, Bret Easton Ellis)",
"Si la gente simplemente ama a los demás solo un poco, pueden ser muy felices (Germinal, Émile Zola)",
"Que diferente sería el mundo si las personas nos preocuparamos solamente un poco por los demás",
"Nunca se sabe lo que la mala suerte te ha salvado de una peor suerte (No es país para viejos, Cormac Mccarthy)",
"No me gusta trabajar – a ningún hombre le gusta – pero me gusta lo que hay en el trabajo – la oportunidad para encontrarte a ti mismo. Tu propia realidad – para ti, no para otros- lo que ningún otro hombre podrá saber (El corazón de las tinieblas, Joseph Conrad)",
"Puede que el trabajo se haga pesado muchas veces, pero trabajar es sinónimo de salud.",
"Alicia: ¿Cuánto tiempo es para siempre? Conejo blanco: A veces solo un segundo (Alicia en el País de las Maravillas, Lewis Carroll)",
"Lo peor de la religión era la gente religiosa (La trama nupcial, Jeffrey Eugenides)",
"La mente hace su propio lugar, y en sí misma puede hacer un cielo del infierno, y un infierno del cielo (Paraíso perdido, John Milton)",
"Ammu dijo que los seres humanos eran criaturas de hábito, y que era increíble el tipo de cosas a las que se podían acostumbrarse (El dios de las pequeñas cosas, Arundhati Roy)",
"Ama a quienes amas mientras los tienes. Eso es todo lo que puedes hacer. Déjalos ir cuando debes. Si sabes cómo amar, nunca escaparas (Mi nombre es memoria, Ann Brashares)",
"Hay que amar y respetar a las personas por las que sientes un cariño especial",
"Hay gente que, cuanto más haces por ellos, menos hacen por sí mismos (Emma, Jane Austen)",
"Si haces mucho por alguien, se acostumbra y se vuelve dependiente. Es un problema que puede prevenirse tomando ciertas precauciones.",
"Hay libros cuyas partes traseras y cubiertas son de lejos la mejor parte (Oliver Twist, Charles Dickes)",
"No todos los libros son obras maestras. Y de hecho, algunos, incluso, no son dignos ni de leer.",
"El mundo era tan reciente, que muchas cosas carecían de nombre, y para mencionarlas había que señarlarlas con el dedo (Cien años de soledad, Gabriel García Marquez)",
"El mundo, y concretamente los seres humanos, hemos ido evolucionando a lo largo de los siglos.",
"Las personas mayores nunca pueden comprender algo por sí solas y es muy aburrido para los niños tener que darles una y otra vez explicaciones (El principito, Antoine de Saint-Exupéry)",
"Cuando sientas deseos de criticar a alguien, recuerda que no todo el mundo ha tenido las mismas oportunidades que tú tuviste (El gran Gatsby, F. Scott Fitzgerald)",
"Criticar es fácil, y las críticas no siempre tienen fundamento. Por eso, antes de llevarlas a cabo, hay que tener bien claros los motivos.",
"La vida cambia rápido. La vida cambia en un instante. Te sientas a cenar y la vida como la conoces termina (El año del pensamiento mágico, Joan Didion)",
"Hay que aprovechar la vida al máximo porque pasa muy rápido. Hay que dejar de lamentarse y disfrutar de ella.",
"¿Sabes lo que ocurre cuando haces daño a la gente? Dijo Ammu. Cuando dañas a la gente, comienzan a quererte menos. Eso es lo que hacen las palabras descuidadas. Hacen que la gente te quiera un poco menos (El dios de las pequeñas cosas, Arundhati Roy)",
"A la gente que te quiere hay que cuidarla. Porque de no ser así, podemos hacerles daño.",
"Cuando tienes miedo pero lo haces de todas formas, eso es valentía (Coraline, Neil Gaiman)",
"La valentía es una cualidad muy positiva que podemos poseer las personas, y nos ayuda a superar grandes obstáculos.",
"Hay que tener cuidado con los libros y lo que hay dentro de ellos, ya que las palabras tienen el poder de cambiarnos (El Ángel mecánico, Cassandra Clare)",
"Las palabras pueden ser muy poderosas y tienen un efecto en nuestros pensamientos.",
"La amistad es sin duda el mejor bálsamo para los dolores de la decepción amorosa (a abadía de Northanger, Jane Austen)",
"Nos contamos historias a nosotros mismos para vivir (El Álbum blanco, Joan Didion)",
"Hablar sin sentido es el único privilegio que la humanidad posee sobre otros organismos. Es al hablar sin sentido cuando uno llega a la verdad. Hablo sin sentido, por tanto soy humano (Crimen y Castigo, Fyodor Dostoevsky)",
"No puedes decir “no” a la gente que amas, no a menudo. Ese es el secreto. Y cuando lo haces, tiene que sonar como un “si” o le tienes que hacer decir “no” (El padrino, Mario Puzo)",
"Es difícil querer a alguien y tener que mencionarle la palabra \"no\". Aún y así, en ocasiones es necesario.",
"Otros escribirán desde la cabeza, pero él escribe desde el corazón, y el corazón siempre le entiende (La leyenda de Sleepy Hollow y otras historias, Washington Irving)",
"Desde el alma es cuando se escriben los mejores relatos, porque te permite dar rienda suelta a la creatividad y a las auténticas emociones.",
"Si quieres saber cómo es un hombre, mira como trata a sus inferiores, no a sus iguales (Harry Potter y el Cáliz, Fuego de J.K. Rowling)",
"Nuestros comportamientos son el reflejo de quienes somos. Son el reflejo de nuestros pensamientos.",
"Todos los finales son también comienzos. Simplemente no lo sabemos en el momento (Las cinco personas que conocerás en el cielo, Mitch Albom)",
"Cuando algo se acaba, es una oportunidad de iniciar algo nuevo. Una oportunidad más para ser feliz.",
"Las varitas son tan poderosas como las brujas que las usan. A algunas brujas les gusta jactarse de que son más grandes y mejores que otra gente (Harry Potter y las Reliquias de la Muerte, J.K. Rowling)",
"No es la varita lo que hace el bien o el mal, sino que son las personas que la usan los que deciden qué hacer con ella.",
"La gente encuentra mucho más sencillo perdonar a otros por estar equivocados que por estar en lo cierto (El príncipe mestizo, J.K. Rowling)",
"Te has enamorado alguna vez? ¿No es horrible? Te hace tan vulnerable. Abre tu pecho y abre tu corazón y significa que alguien puede entrar en ti y deshacerte (Las benévolas, Neil Gaiman)",
"Cerrarse al amor es un gran sufrimiento y puede causar problemas emocionales graves. Por eso, hay que abrirse y amar.",
"La felicidad se puede encontrar, incluso en los tiempos más oscuros, solo si se recuerda encender la luz (El Prisionero de Azkaban, J.K. Rowling)",
"Aun en los malos momentos, hay que encender el interruptor de la felicidad para no vivir anclados en el sufrimiento.",
"Por la tarde fue a ver al cine “El Señor de los Anillos”, la cuál no había tenido tiempo para ver antes. Pensó que los orcos, a diferencia de los seres humanos, eran criaturas simples y sin complicaciones (La Chica del Dragón Tatuado, Stieg Larsson)",
"Los seres humanos somos expertos en el arte de complicarnos la vida.",
"Resulta extraño pensar que, cuando uno teme algo que va a ocurrir y quisiera que el tiempo empezara a pasar más despacio, el tiempo suele pasar más deprisa (Harry Potter y el Cáliz de fuego, JK Rowling)",
"Recrearse en las preocupaciones no es nada positivo. Es más, pensar en negativo puede llevar a lo que se conoce como la profecía autocumplida.",
"Reflexionar serena, muy serenamente, es mejor que tomar decisiones desesperadas (La Metamorfosis, Franz Kafka)",
"La autorreflexión es clave para e bienestar mental y emocional.",
"La impresionó tanto su enorme desnudez tarabiscoteada que sintió el impulso de retrocede (Cien Años de Soledad, Gabriel García Márquez)",
"Es mejor mirar al cielo que vivir allí (Desayuno con diamantes, Truman Capote)",
"El cielo está para contemplarlo. Vivir allí significaría que nuestro final ha llegado.",
"A pesar de ti, de mi y del mundo que se desquebraja, yo te amo (Lo que el Viento se Llevó, Margareth Mitchell)",
"Cuando el amor es tan intenso, no hay nada que pueda separarte de esa persona tan especial.",
"La alegría causa a veces un efecto extraño; oprime al corazón casi tanto como el dolor (El Conde de Montecristo, Alejandro Dumas)",
"Caminando en línea recta no puede uno llegar muy lejos (El Principito, Antoine de Saint-Exupèry)",
"Si queremos crecer, hay que probar caminos distintos. En otras palabras, salir de la zona de confort.",
"Que cosa tan traicionera pensar que una persona es más que una persona (Paper Towns, John Green)",
"Hay que ser humilde en esta vida, porque no todo el mundo tiene las mismas oportunidades.",
"Se debe pedir a cada cual, lo que está a su alcance realizar (El Principito, Antoine de Saint-Exupèry)",
"No hay que ser duro con la gente. No se puede esperar más de alguien de lo que puede ofrecer.",
"Cuando una mujer se vuelve a casar es porque detestaba a su primer marido. Cuando un hombre se vuelve a casar es porque adoraba a su primera mujer. Las mujeres prueban suerte; los hombres arriesgan la suya (El Retrato de Dorian Gray, Oscar Wilde)",
"La muerte destroza al hombre: la idea de la muerte le salva (Howards End, E. M. Forster)",
"En ocasiones, pensar en la muerte puede ayudar a las personas a no cometer excesivos riesgos que podrían acabar mal.",
"Cierto que casi siempre se encuentra algo, si se mira, pero no siempre es lo que uno busca (El Hobbit, J.R.R. Tolkien)",
"Estar en movimiento nos brinda nuevas oportunidades. A pesar de que siempre no son lo que habíamos planeado, puede que sean positivas.",
"La dicha suprema de la vida es la convicción de que somos amados, amados por nosotros mismos; mejor dicho amados a pesar de nosotros (Los miserables, Victor Hugo)",
"No es fácil amarse a uno mismo, pero a veces somos nosotros mismos nuestros propios enemigos.",
"Ningún hombre puede pensar claramente cuando sus puños están cerrados (George Jean Nathan)",
"Un hombre que es un maestro en la paciencia es un maestro en todo lo demás (George Savile)",
"El poder de la paciencia y de la habilidad de gestionar bien el tiempo, en una frase sabia.",
"Alguien que no cree en los milagros no es realista (David Ben-Gurión)",
"No hay una visión más triste que la de un joven pesimista (Mark Twain)",
"La esperanza es un buen desayuno, pero una mala cena (Francis Bacon)",
"La esperanza como algo que tiene doble filo: resulta positiva cuando todo un mundo de posibilidades se abre ante nosotros, pero no tanto cuando es el último recurso.",
"La educación es el movimiento de la oscuridad a la luz (Allan Bloom)",
"El riesgo de una mala decisión es preferible al terror de la indecisión (Maimónides)",
"Una mente necesita un libro como una espada necesita su piedra de afilar (George R. R. Martin)",
"Lo que hoy está comprobado una vez solo pudo ser imaginado (William Blake)",
"Solo los educados son libres (Epicteto)",
"Todo conocimiento resulta hiriente (Cassandra Clare)",
"La honestidad es el primer capítulo del libro de la sabiduría (Thomas Jefferson)",
"Toda sociedad está a tres comidas del caos (Lenin)",
"No se dice rompí a comer o rompí a caminar. Rompes a llorar o a reír. Creo que vale la pena hacerse añicos por esos sentimientos (Albert Espinosa)",
"El tiempo es aquello que más queremos y también lo que peor utilizamos (William Penn)",
"La libertad nunca es dada; siempre es ganada (Asa Philip Randolph)",
"Una vez tienes algo que hacer, es mejor hacerlo que vivir con el miedo a causa de eso (Joe Abercrombie)",
"El hombre es la única criatura que se niega a ser quien es (Albert Camus)",
"La creatividad requiere que la valentía se desprenda de las certezas (Erich Fromm)"
"La mejor parte de la belleza es aquella que ninguna imagen puede expresar (Francis Bacon)",
"Aquellos que no conocen la historia están condenados a repetirla (Edmund Burke)",
"Nada es tan increíble como para que la oratoria no lo pueda transformar en aceptable (Cicerón)",
"De una pequeña chispa puede prender una llama (Dante)"
];